[package]
name = "tacklebox-pico"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m-rt = "0.7.6"
embassy-executor = { version = "0.10.0", features = ["platform-cortex-m", "executor-thread"] }
embassy-rp = { version = "0.10.0", features = ["rp2040", "time-driver", "critical-section-impl"] }
embassy-sync = "0.8.0"
embassy-time = { version = "0.5.1", features = ["tick-hz-1_000_000"] }
embassy-usb = "0.6.0"
panic-halt = "1.0.0"
portable-atomic = { version = "1.15.0", default-features = false, features = ["critical-section"] }
postcard = { workspace = true }
serde = { workspace = true }
static_cell = "2.1.1"

[profile.dev]
panic = "abort"
opt-level = "s"

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
codegen-units = 1
